//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Blend.SampleData.DesignDataSource
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class DesignDataSource { }
#else

	public class DesignDataSource : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public DesignDataSource()
		{
			try
			{
				Uri resourceUri = new Uri("ms-appx:/SampleData/DesignDataSource/DesignDataSource.xaml", UriKind.RelativeOrAbsolute);
				Windows.UI.Xaml.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private Items _Items = new Items();

		public Items Items
		{
			get
			{
				return this._Items;
			}
		}
	}

	public class Items : System.Collections.ObjectModel.ObservableCollection<ItemsItem>
	{ 
	}

	public class ItemsItem : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Content = string.Empty;

		public string Content
		{
			get
			{
				return this._Content;
			}

			set
			{
				if (this._Content != value)
				{
					this._Content = value;
					this.OnPropertyChanged("Content");
				}
			}
		}

		private string _Title = string.Empty;

		public string Title
		{
			get
			{
				return this._Title;
			}

			set
			{
				if (this._Title != value)
				{
					this._Title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}

		private Windows.UI.Xaml.Media.ImageSource _BackgroundImage = null;

		public Windows.UI.Xaml.Media.ImageSource BackgroundImage
		{
			get
			{
				return this._BackgroundImage;
			}

			set
			{
				if (this._BackgroundImage != value)
				{
					this._BackgroundImage = value;
					this.OnPropertyChanged("BackgroundImage");
				}
			}
		}
	}
#endif
}
